---
# Main configuration file for plugin [SimpleTitle] for PocketMine-MP (PMMP) software
# Made by @LewBr (Leonardo Santos)

#Basic plugin abbreviations to get a function or something related to the plugin:
#1. {player} - returns the name of the player who entered the related server;
#2. & - used a few times in some of my plugins, it would be a "translation" of the ยง symbol, so there may be no errors in saving the file.

#Not recommended to delete this part, otherwise the plugin will not work properly.
configurations:
 #Symbol to be used to change the color of the text by default as stated earlier would be ยง but can be changed by your preference in this plugin
 symbol_color: "&"

 #Change of the first text (major)
 #Exemple:
 #first_title: "&6Hello {player}" code hex &6 in the case would be gold color
 first_title: "text_1"

 #Change of the second text (minor)
 #Exemple:
 #second_title: "&7Welcome!"
 second_title: "text_2"

 #Time the message will be on the player's screen, calculated in milliseconds (default: 100 milliseconds)
 time: 100
...
